---

- name: Create logging manifest directory on bastion
  file:
    path: "{{ manifest_dir_path | default('/tmp/logging/files', true) }}"
    state: directory
    mode: '0755'
    
- name: Clean up logging resources
  include_tasks: "{{ role_path }}/files/clf-cleanup.yml"
  when: clf_clean_up

- name: Deploy logging stack
  include_tasks: "{{ role_path }}/files/loggingstack.yml"
  when: 
    - (ocp_cluster_logging or cluster_log_forwarder) and not clf_clean_up
    