---
# Set elasticsearch_server_url
- block:
    - name: Check Elasticsearch URL is reachable
      ansible.builtin.uri:
        url: "{{ elasticsearch_url }}"
        method: GET
        validate_certs: false
        timeout: 10
      register: es_op
      failed_when: false

    - name: Set Elasticsearch server URL
      ansible.builtin.set_fact:
        elasticsearch_server_url: "{{ elasticsearch_url }}"
      when:
        - not es_op.failed

    - name: Fail if Elasticsearch URL is unreachable
      ansible.builtin.fail:
        msg: "Elasticsearch URL is invalid or unreachable: {{ elasticsearch_url }}"
      when:
        - es_op.failed

  when: (elasticsearch_url | default('') | trim | length) > 0
    
# Set loki_server_url
- block:
    - name: Check Loki URL is reachable or not
      ansible.builtin.uri:
        url: "{{ loki_url }}/ready"
        method: GET
        validate_certs: false
        timeout: 10
      register: loki_op
      failed_when: false

    - name: Set Loki server URL
      ansible.builtin.set_fact:
        loki_server_url: "{{ loki_url }}"
      when:
        - not loki_op.failed
        
    - name: Fail if Loki URL is unreachable
      ansible.builtin.fail:
        msg: "Loki URL is invalid or unreachable: {{ loki_url }}"
      when:
        - loki_op.failed

  when: (loki_url | default('') | trim | length) > 0

# Set kafka_server_url
- block:
    - name: Set Kafka host and port
      ansible.builtin.set_fact:
        kafka_server_url: "{{ kafka_url }}"
        kafka_host: "{{ kafka_url | regex_replace('^tcp://', '') | split(':') | first }}"
        kafka_port: "{{ kafka_url | split(':') | last | int }}"

    - name: Check Kafka TCP port is reachable
      ansible.builtin.wait_for:
        host: "{{ kafka_host }}"
        port: "{{ kafka_port }}"
        timeout: 10
      register: kafka_op
      failed_when: false

    - name: Fail if Kafka URL is unreachable
      fail:
        msg: "Kafka URL is invalid or unreachable"
      when: kafka_op.failed
  when: (kafka_url | default('') | trim | length) > 0

# Set syslog_server_url
- block:
    - name: Set Syslog host and port
      ansible.builtin.set_fact:
        syslog_server_url: "{{ syslog_url }}"
        syslog_host: "{{ syslog_url | regex_replace('^tcp://', '') | split(':') | first }}"
        syslog_port: "{{ syslog_url | split(':') | last | int }}"

    - name: Check Syslog TCP port is reachable
      ansible.builtin.wait_for:
        host: "{{ syslog_host }}"
        port: "{{ syslog_port }}"
        timeout: 10
      register: syslog_op
      failed_when: false

    - name: Fail if Syslog URL is unreachable
      fail:
        msg: "Syslog URL is invalid or unreachable"
      when: syslog_op.failed
  when: (syslog_url | default('') | trim | length) > 0
    

# Set fluentd_server_url
- block:
    - name: Check Fluentd TCP port is reachable
      wait_for:
        host: "{{ fluentd_url | regex_replace('^tcp://', '') | split(':') | first }}"
        port: "{{ fluentd_url | split(':') | last | int }}"
        timeout: 10
      register: fluentd_op
      failed_when: false

    - name: Set Fluentd server URL
      set_fact:
        fluentd_server_url: "{{ fluentd_url }}"
      when:
        - not fluentd_op.failed
        
    - name: Fail if Fluentd URL is unreachable
      fail:
        msg: "Fluentd URL is invalid or unreachable"
      when: fluentd_op.failed
      
  when: (fluentd_url | default('') | trim | length) > 0

# Check if the secret for AWS is exists and set_fact
- block:
  - name: Check if secret "{{ cloudwatch_secret }}" is exists in the openshift-logging namespace
    shell: oc get secret "{{ cloudwatch_secret }}" -n openshift-logging 
    register: aws_secret

  # Set cw_secret
  - name: Set cloudwatch secret
    set_fact:
      cw_secret: "{{ cloudwatch_secret }}"
    when: not aws_secret.failed
    
  # Set aws_region
  - name: Set aws_region
    set_fact:
      aws_cw_region: "{{ aws_region | default('ap-south-1', true)}}"
    when: not aws_secret.failed

  - name: Fail if AWS CloudWatch secret is not present
    fail:
      msg: "AWS CloudWatch secret is not present"
    when: aws_secret.failed
  when: (cloudwatch_secret | default('') | trim | length) > 0
